name: Fast API docker build push
on: 
  push:
    branches:[ main ]
    
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
    - uses: actions/checkout@v3
    - name: Build docker img for FastApi
      run: docker build -t '${{secrets.DOCKER_USERNAME}'/fastapi-docker:'#{{github.sha}}' .

    - name: Loggin to the Docker hub
      run: docker login --username username '${{secrets.DOCKER_USERNAME}}' --password '${{secrets.DOCKER_PASSWORD}}'
    
    - name: Push the image to the docker hub
      run: docker push '{{secrets.DOCKER_USERNAME}'/fastapi-docker:'#{{github.sha}}'